name: Excavator

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  excavator:
    name: Excavator
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - name: Excavate
        uses: Ash258/Scoop-GithubActions@stable-win
        env:
          SHOVEL: "1"
          GITH_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
